theme: minima

<html lang="en"><head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"><!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Your awesome title | Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.</title>
<meta name="generator" content="Jekyll v4.3.2">
<meta property="og:title" content="Your awesome title">
<meta name="author" content="GitHub User">
<meta property="og:locale" content="en_US">
<meta name="description" content="Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.">
<meta property="og:description" content="Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.">
<meta property="og:site_name" content="Your awesome title">
<meta property="og:type" content="website">
<meta name="twitter:card" content="summary">
<meta property="twitter:title" content="Your awesome title">
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebSite","author":{"@type":"Person","name":"GitHub User"},"description":"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.","headline":"Your awesome title","name":"Your awesome title","url":"/minima/"}</script>
<!-- End Jekyll SEO tag -->
<link id="stylesheet" rel="stylesheet" href="https://jekyll.github.io/minima/assets/css/style.css"><link type="application/atom+xml" rel="alternate" href="/minima/feed.xml" title="Your awesome title">
</head>
<body><header class="site-header">

  <div class="wrapper"><a class="site-title" rel="author" href="/minima/">Top 5 Staple Taiwanese Foods</a></div>
</header>
<main class="page-content" aria-label="Content">
      <div class="wrapper">
        <div class="home">



  

    </div>

      </div>
    </main><footer class="site-footer h-card">
  <data class="u-url" href="/minima/"></data>

  <div class="wrapper">

    <div class="footer-col-wrapper">
      
      <div class="footer-col">
        <p>Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
</p>
      </div>
    </div>

    

  </div>

</footer>



<script>
  document.getElementById("skin-switch-container").style.display = "block";
  var metaTag = document.getElementById("stylesheet");
  var SSHref = metaTag.href;
  var SSName = (SSHref.substring(SSHref.lastIndexOf('/') + 1));

  document.getElementById("skin-switch").value = SSName;

  function changeSkin() {
    metaTag.href = SSHref.replace(SSName, event.target.value);
  }
</script>



</body></html>
